version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.simple
    environment:
      PORT: 8000
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

# No database needed for stateless demo!
networks:
  default:
    name: monopoly-deal-simple