[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip", "bash"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/static",
  "cp -r frontend/dist/* backend/static/"
]

[start]
cmd = "cd backend && python3 main.py"