[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python main_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
PYTHONPATH = "backend"